theme: jekyll-theme-minimal

# Name of website
title: Kenneth Bunker

# Short description of your site
description: Peronal website

# List of links in the navigation bar
navbar-links:
  About Me: "aboutme"
  Resources:
    - Beautiful Jekyll: "http://deanattali.com/beautiful-jekyll/"
    - Learn markdown: "http://www.markdowntutorial.com/"
  Author's home: "http://deanattali.com"



# Select your active Social Network Links
social-network-links:
  rss: true
  email: "kabunker@gmail.com"
  github: kennethbunker
  twitter: kennethbunker
